version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: barbershop
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
